"""Initial migration

Revision ID: 6d629c273ff4
Revises: 
Create Date: 2025-10-07 13:35:44.254403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import DateTime


# revision identifiers, used by Alembic.
revision: str = '6d629c273ff4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('lang_code', sa.String(length=10), nullable=False),
    sa.Column('lang_name', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISABLED', name='statustype'), nullable=False),
    sa.Column('create_datetime', DateTime(timezone=True), nullable=False),
    sa.Column('update_datetime', DateTime(timezone=True), nullable=False),
    sa.Column('project_metadata', sa.JSON(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('create_datetime', DateTime(timezone=True), nullable=False),
    sa.Column('update_datetime', DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('create_datetime', DateTime(timezone=True), nullable=False),
    sa.Column('update_datetime', DateTime(timezone=True), nullable=False),
    sa.Column('access_type', sa.Enum('OWNER', 'COLLABORATOR', 'VIEWER', name='projectaccesstype'), nullable=True),
    sa.Column('access_rights', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_access')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
